In [1]:
import sys
sys.path.append("../src")

from event_selections import *
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
sys.path.append("../src")
c_folder="../../data/calibration/"
d_folder="../../data/runData"
r_n=305
p_folder="../../plots/run_"+str(r_n)

In [3]:
mip_df=pd.read_csv(c_folder+"mip.csv", sep=',')

In [4]:
mip_df

,layer,strip,end,multiplier,mpv,eta,sigma,A
0,1,0,0,17,419.238027,44.313937,86.207923,1427.859925
1,1,1,0,14,434.693762,48.724876,83.669725,2539.413286
2,1,2,0,16,404.510612,43.863074,75.117016,6181.196115
3,1,3,0,15,377.615662,46.833564,55.816501,8406.889916
4,1,4,0,10,460.481195,52.604066,90.458689,4504.040397
...,...,...,...,...,...,...,...,...
379,19,7,1,10,584.690392,61.431459,12.582419,1824.182527
380,19,8,1,10,627.148337,57.647316,84.558306,639.993205
381,19,9,1,10,616.044689,59.808158,84.012930,396.806976
382,19,10,1,10,574.447876,51.604680,71.661481,293.847416
383,19,11,1,10,661.962282,68.610454,97.939237,141.276719

In [5]:
mpv_1=mip_df[mip_df['end']==1].mpv

In [6]:
mip_fixed=mip_df[mip_df['end']==0]
mip_fixed=mip_fixed.rename(columns={"mpv": "mpv_end0"})
mip_fixed=mip_fixed.assign(mpv_end1=mpv_1.values)


mip_fixed.drop(["eta", "sigma", "A","multiplier", "end"], axis=1, inplace=True)
mip_fixed.reset_index(inplace=True, drop=True)

In [8]:
mip_fixed.to_csv(c_folder+"mip_fixed.csv", index=False)

In [3]:
pedestal_df=pd.read_csv(c_folder+"pedestal.csv", sep=',')

In [4]:
pedestal_df

,layer,strip,end,pedestal,mean,std_dev,pedestal_per_time_sample,pedestal_per_time_sample_mean,pedestal_per_time_sample_std_dev
0,1,0,0,760,-1.027374,9.674627,95,94.874186,1.158700
1,1,0,1,840,-7.573053,11.046368,105,104.256295,1.674440
2,1,1,0,760,-2.802681,14.564194,95,94.610470,1.025559
3,1,1,1,760,13.318374,18.856047,95,95.583513,1.358078
4,1,2,0,728,8.016915,10.387670,91,92.069458,1.730582
...,...,...,...,...,...,...,...,...,...
379,19,9,1,824,-7.199062,9.375246,103,102.102113,1.739407
380,19,10,0,728,-4.817720,9.138480,91,90.590485,1.308983
381,19,10,1,824,-1.787860,9.243012,103,102.861754,1.341918
382,19,11,0,792,-3.005107,11.286028,99,99.142197,1.349934
383,19,11,1,760,5.906942,9.002523,95,95.405753,1.193207

In [5]:
ped_1=pedestal_df[pedestal_df['end']==1].pedestal
std_dev_1=pedestal_df[pedestal_df['end']==1].std_dev
ppts_1=pedestal_df[pedestal_df['end']==1].pedestal_per_time_sample
ppts_std_dev_1=pedestal_df[pedestal_df['end']==1].pedestal_per_time_sample_std_dev

In [6]:
ped_fixed=pedestal_df[pedestal_df['end']==0]
ped_fixed=ped_fixed.rename(columns={"pedestal": "pedestal_end0",
                                    "std_dev" : "std_dev_end0",
                                    "pedestal_per_time_sample":"pedestal_per_time_sample_end0",
                                    "pedestal_per_time_sample_std_dev":"pedestal_per_time_sample_std_dev_end0"})
ped_fixed=ped_fixed.assign(pedestal_end1=ped_1.values)
ped_fixed=ped_fixed.assign(std_dev_end1=std_dev_1.values)
ped_fixed=ped_fixed.assign(pedestal_per_time_sample_end1=ppts_1.values)
ped_fixed=ped_fixed.assign(pedestal_per_time_sample_std_dev_end1=ppts_std_dev_1.values)

ped_fixed.drop(["mean", "pedestal_per_time_sample_mean", "end"], axis=1, inplace=True)
ped_fixed.reset_index(inplace=True, drop=True)

In [7]:
ped_fixed.to_csv(c_folder+"pedestal_fixed.csv", index=False)